flowchart LR
    Start([Start]) --> Specify

    subgraph Specification
        Specify[Specify] --> SpecifyCheck{Any items need clarification?}
        SpecifyCheck -- Yes --> Clarify[Clarify]
        SpecifyCheck -- No --> SpecificationAccept
        Clarify --> ClarifyCheck{Any items need clarification?}
        ClarifyCheck -- Yes --> Clarify
        ClarifyCheck -- No --> SpecificationAccept
    end

    SpecificationAccept[Accept] --> Plan

    subgraph Planning
        Plan[Plan]
        Plan --> PlanningAccept[Accept]
    end

    PlanningAccept --> Implement

    subgraph Implementation
        Implement[Implement] --> TDDLoop

        subgraph TDDLoop [Red-Green-Refactor]
            Red[Red] --> Green[Green] --> Refactor[Refactor] --> Red
        end
    end

    TDDLoop --> ImplementationAccept[Accept]
    ImplementationAccept --> End([End])
